version: '3'
services:
  estimator:
    build:
      context: ./estimator
    ports:
      - "8000:8000"
    volumes:
      - ./estimator:/app/estimator
  server:
    build:
      context: ./server
    ports:
      - "8080:5000"
    volumes:
      - ./server:/app/server
